# Generated by Django 4.0 on 2022-01-07 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=128, unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('user_nick_name', models.CharField(max_length=30)),
                ('user_phone_num', models.CharField(max_length=30, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Man'), ('G', 'Girl')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('community_id', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='practice.community')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('community_id', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='practice.community')),
                ('writer', models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='author_id',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='practice.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='practice.post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blocked_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
                ('community_id', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='practice.community')),
            ],
        ),
    ]
