# Generated by Django 4.0 on 2021-12-31 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime(2021, 12, 31, 6, 22, 32, 824390, tzinfo=utc))),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
