# Generated by Django 4.0 on 2022-01-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_migrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone_nub',
            new_name='user_phone_num',
        ),
    ]
