# Generated by Django 4.0 on 2022-01-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(db_column='subject', default='', on_delete=django.db.models.deletion.CASCADE, to='practice.subject'),
        ),
    ]
