# Generated by Django 4.0 on 2021-12-31 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 12, 31, 6, 24, 21, 383335, tzinfo=utc)),
        ),
    ]
