# Generated by Django 4.0 on 2022-01-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_rename_user_phone_nub_user_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='author_id',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='practice.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, to='practice.user'),
        ),
    ]
