# Generated by Django 4.0 on 2022-01-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_rename_subject_post_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', default='', on_delete=django.db.models.deletion.CASCADE, to='practice.subject'),
        ),
    ]
