# Generated by Django 4.0 on 2022-01-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_post_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocked',
        ),
        migrations.CreateModel(
            name='Blocked_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
                ('community_id', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, to='practice.community')),
            ],
        ),
    ]
