# Generated by Django 4.0 on 2022-01-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_post_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
