# Generated by Django 4.0 on 2022-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_rename_subject_id_post_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone_num',
            field=models.CharField(max_length=30),
        ),
    ]
