# Generated by Django 4.0 on 2022-01-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_post_options_remove_user_blocked_blocked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked_user',
            name='community_id',
            field=models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='practice.community'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='practice.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='community_id',
            field=models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='practice.community'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='community_id',
            field=models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='practice.community'),
        ),
    ]
