# Generated by Django 4.0 on 2022-01-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_user_user_email_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='user_id',
        ),
    ]
